fix missing facility specification
 * default of nsls2 results in PASS API exception:
   httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://passservices.bnl.gov/....../NSLS-II/300047/null'